Alias /phpmyadmin "C:/Laragon/www/LaX/etc/apps/phpMyAdmin/"
Alias /phpMyAdmin "C:/Laragon/www/LaX/etc/apps/phpMyAdmin/"

<Directory "C:/Laragon/www/LaX/etc/apps/phpMyAdmin/">
    Options Indexes FollowSymLinks ExecCGI
    AllowOverride All
    Require all granted
    DirectoryIndex index.php
</Directory>
