location /phpmyadmin {
    alias C:/Laragon/www/LaX/etc/apps/phpMyAdmin/;
    index index.php;
}

location ~ ^/phpmyadmin/(.+\.php)$ {
    alias C:/Laragon/www/LaX/etc/apps/phpMyAdmin/$1;
    include C:/Laragon/www/LaX/etc/nginx/fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $request_filename;
    fastcgi_index index.php;
    fastcgi_pass php_upstream;
}
