server {
    listen 80 default_server;
    server_name localhost;
    root "C:/Laragon/www/LaX/www";
    index index.html index.htm index.php;
    client_max_body_size 2000M;
    include "C:/Laragon/www/LaX/etc/nginx/alias/*.conf";

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
        autoindex on;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass php_upstream;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location ~ /\.ht { deny all; }
}
